version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ../mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
       - "13306:3306"

   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - ../sessions:/sessions

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wp-hello
     ports:
       - "8001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ../public:/var/www/html
       - ../log:/var/log
volumes:
    db_data:
